remote_theme: pmarsceill/just-the-docs

title: C-Play
description: Open source media player for clustered environments
logo: "/assets/C_play_transparent.png"
favicon_ico: "/assets/C_play_transparent.ico"

search_tokenizer_separator: /[\s/]+/
#heading_anchors: true
footer_content: "Copyright &copy; 2021-2024 Erik Sund√©n. Distributed by an <a href=\"https://github.com/c-toolbox/C-Play/tree/master/LICENSE.txt\">GNU General Public License v3.0.</a>"
color_scheme: "dark"

aux_links:
  "C-Play on GitHub":
    - "//github.com/c-toolbox/C-Play"

plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed